#!/usr/bin/env bash
# =============================================================================
#  MediaServer Install Script
#  Installs: Jellyfin · Audiobookshelf · Navidrome
#  Requirements: Ubuntu Server, root or sudo
# =============================================================================
set -euo pipefail

# ── Colors ────────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; BOLD='\033[1m'; NC='\033[0m'

log()  { echo -e "${GREEN}[OK]${NC} $*"; }
info() { echo -e "${BLUE}[i]${NC} $*"; }
warn() { echo -e "${YELLOW}[!]${NC} $*"; }
err()  { echo -e "${RED}[ERR]${NC} $*"; exit 1; }
step() { echo -e "\n${BOLD}${BLUE}== $* ==${NC}"; }

# ── Root check ────────────────────────────────────────────────────────────────
[[ $EUID -ne 0 ]] && err "Run as root: sudo bash install_media.sh"

# ── Paths ─────────────────────────────────────────────────────────────────────
HOMELAB=/home/homelab
DATA=/home/homelab_data
SHARED=/home/data

# ── Detect server IP ──────────────────────────────────────────────────────────
SERVER_IP=$(hostname -I | awk '{print $1}')
info "Detected server IP: ${SERVER_IP}"

# =============================================================================
#  1. DOCKER
# =============================================================================
step "1. Installing Docker"
if ! command -v docker &>/dev/null; then
    apt-get update -qq
    apt-get install -y -qq ca-certificates curl gnupg lsb-release
    curl -fsSL https://get.docker.com | sh
    systemctl enable --now docker
    log "Docker installed"
else
    log "Docker already present: $(docker --version)"
fi

if ! docker compose version &>/dev/null; then
    apt-get install -y -qq docker-compose-plugin
    log "docker-compose-plugin installed"
else
    log "Docker Compose already present"
fi

# =============================================================================
#  2. DIRECTORIES
# =============================================================================
step "2. Creating directory structure"
mkdir -p "$HOMELAB"
mkdir -p "$DATA"/{jellyfin,audiobookshelf,navidrome}
mkdir -p "$DATA"/jellyfin/{config,cache}
mkdir -p "$DATA"/audiobookshelf/{config,metadata}
mkdir -p "$DATA"/navidrome/data
mkdir -p "$SHARED"/{media,music,audiobooks}
chmod -R 755 "$DATA" "$SHARED"
log "Directories created"

# =============================================================================
#  3. GENERATE .env
# =============================================================================
step "3. Generating .env"

if [[ -f "$HOMELAB/.env" ]]; then
    warn ".env already exists -- skipping to avoid overwrite"
else

cat > "$HOMELAB/.env" <<EOF
# =============================================================
#  MediaServer .env  --  DO NOT COMMIT TO GIT
#  Generated: $(date)
# =============================================================

# -- Server --------------------------------------------------
SERVER_IP=${SERVER_IP}
TZ=Europe/Ljubljana

# -- Jellyfin ------------------------------------------------
JELLYFIN_PUBLISHED_SERVER_URL=http://${SERVER_IP}:8060

# -- Navidrome -----------------------------------------------
ND_SESSIONTIMEOUT="24h"
ND_LOGLEVEL="info"
ND_SCANSCHEDULE="@every 1m"
ND_AUTOIMPORTPLAYLISTS="true"
ND_SPOTIFY_ID=
ND_SPOTIFY_SECRET=
ND_LASTFM_APIKEY=
ND_LASTFM_SECRET=
EOF

chmod 600 "$HOMELAB/.env"
log ".env created"
fi

# =============================================================================
#  4. GENERATE docker-compose.yml
# =============================================================================
step "4. Generating docker-compose.yml"

# Load .env so path variables are available for volume mounts
source "$HOMELAB/.env"

cat > "$HOMELAB/docker-compose.yml" <<COMPOSE
# =============================================================
#  MediaServer -- docker-compose.yml
#  Generated by install_media.sh -- do not edit manually
# =============================================================

services:

# =============================================================
#  JELLYFIN  --  port 8060
# =============================================================
  jellyfin:
    image: ghcr.io/jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "8060:8096"
    volumes:
      - ${DATA}/jellyfin/config:/config
      - ${DATA}/jellyfin/cache:/cache
      - ${SHARED}/media:/media:ro
      - ${SHARED}/music:/music:ro
      - ${SHARED}/audiobooks:/audiobooks:ro
    environment:
      TZ: \${TZ}
      JELLYFIN_PublishedServerUrl: \${JELLYFIN_PUBLISHED_SERVER_URL}
    networks:
      - media-net

# =============================================================
#  AUDIOBOOKSHELF  --  port 8061
# =============================================================
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    restart: unless-stopped
    ports:
      - "8061:80"
    volumes:
      - ${DATA}/audiobookshelf/config:/config
      - ${DATA}/audiobookshelf/metadata:/metadata
      - ${SHARED}/audiobooks:/audiobooks
      - ${SHARED}/media:/media:ro
    environment:
      TZ: \${TZ}
    networks:
      - media-net

# =============================================================
#  NAVIDROME  --  port 8062
# =============================================================
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    restart: unless-stopped
    user: "1000:1000"
    ports:
      - "8062:4533"
    volumes:
      - ${DATA}/navidrome/data:/data
      - ${SHARED}/music:/music:ro
    environment:
      ND_MUSICFOLDER: /music
      ND_DATAFOLDER: /data
      ND_SCANSCHEDULE: \${ND_SCANSCHEDULE}
      ND_LOGLEVEL: \${ND_LOGLEVEL}
      ND_SESSIONTIMEOUT: \${ND_SESSIONTIMEOUT}
      ND_AUTOIMPORTPLAYLISTS: \${ND_AUTOIMPORTPLAYLISTS}
      ND_SPOTIFY_ID: \${ND_SPOTIFY_ID}
      ND_SPOTIFY_SECRET: \${ND_SPOTIFY_SECRET}
      ND_LASTFM_APIKEY: \${ND_LASTFM_APIKEY}
      ND_LASTFM_SECRET: \${ND_LASTFM_SECRET}
      TZ: \${TZ}
    networks:
      - media-net

# =============================================================
#  NETWORKS
# =============================================================
networks:
  media-net:
    driver: bridge
COMPOSE

log "docker-compose.yml created"

# =============================================================================
#  5. START SERVICES
# =============================================================================
step "5. Starting services"
cd "$HOMELAB"
docker compose --env-file .env up -d --remove-orphans
log "All services started"

# =============================================================================
#  6. SUMMARY
# =============================================================================
step "6. Summary"
echo ""
echo -e "${BOLD}+----------------------------------------------------------+${NC}"
echo -e "${BOLD}|          MediaServer -- Installed Services               |${NC}"
echo -e "${BOLD}+----------------------------------------------------------+${NC}"
printf "| %-16s  http://%-30s|\n" "Jellyfin"       "${SERVER_IP}:8060"
printf "| %-16s  http://%-30s|\n" "Audiobookshelf" "${SERVER_IP}:8061"
printf "| %-16s  http://%-30s|\n" "Navidrome"      "${SERVER_IP}:8062"
echo -e "${BOLD}+----------------------------------------------------------+${NC}"
echo -e "| .env:     ${HOMELAB}/.env                        |"
echo -e "| Compose:  ${HOMELAB}/docker-compose.yml          |"
echo -e "| Data:     ${DATA}/                    |"
echo -e "| Media:    ${SHARED}/media/                       |"
echo -e "| Music:    ${SHARED}/music/                       |"
echo -e "| Podcasts: ${SHARED}/audiobooks/                  |"
echo -e "${BOLD}+----------------------------------------------------------+${NC}"
echo ""
warn "Jellyfin needs 1-2 minutes to initialize before it is accessible."
warn "Place media files in ${SHARED}/{media,music,audiobooks}/ before scanning."
warn ".env contains secrets -- secure the file and do not commit it to git."
echo ""
log "Installation complete."
